image:
  repository: ghcr.io/vamor/vamolt-api
  tag: "sha-42a45de597a791e8061bb51a5ea8da29ecc4a917"

replicaCount: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
container:
  port: 8080
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
