apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: vamolt-root
spec:
  project: default
  source:
    repoURL: https://github.com/vamor/VaMolt-gitops.git
    targetRevision: master
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
