apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vamolt-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vamor/VaMolt-gitops.git
    targetRevision: main
    path: apps/vamolt-api
    helm:
      valueFiles:
        - values/dev/vamolt-api-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
