apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vamolt-api-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vamolt-dev
  sources:
    - repoURL: https://github.com/vamor/vamolt.git
      targetRevision: main        # of 'master' als jouw app-repo zo heet
      path: charts/vamolt-api
      helm:
        valueFiles:
          - $values/values/dev/vamolt-api-values.yaml
    - repoURL: https://github.com/vamor/VaMolt-gitops.git
      targetRevision: master      # jouw gitops-branch
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true